
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

CREATE TABLE IF NOT EXISTS `mydb`.`food` (
  `Idfood` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `imgUrl` VARCHAR(445) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(445) NOT NULL,
  PRIMARY KEY (`Idfood`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `userLastName` VARCHAR(45) NOT NULL,
  `userAdress` VARCHAR(445) NOT NULL,
  `userNumber` VARCHAR(445) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `cartId` INT NOT NULL AUTO_INCREMENT,
  `foodOrder` INT NOT NULL,
  `orderStatus` VARCHAR(445) NOT NULL,
  `food_Idfood` VARCHAR(445) NOT NULL,
  `customer_iduser` INT NOT NULL,
  PRIMARY KEY (`cartId`),
  CONSTRAINT `fk_cart_customer`
    FOREIGN KEY (`customer_iduser`)
    REFERENCES `mydb`.`customer` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
